### ISSUE TITLE
The march meetup isn't showing up on the site

### ISSUE THREAD

**Issue by godber** [desertpy/desertpy-pelican#21]
I haven't had a chance to look into this yet, but the website doesn't show the march meetup for some reason.

**Comment by godber** [comment]
@nelsonjchen if you have some time and the inclination, feel free to take a look.

**Comment by nelsonjchen** [comment]
It's there, but the order is screwed up. The posts are generated from the date the original event was created, not the event date itself. I'll try to correct that.

**Comment by godber** [comment]
Oh, sure enough, it is there.

That was the Draft Creation Date ... I don't really know what timestamps are exposed by the API.

Let me know if it can't be changed.  I may need to think about this ... for instance ... do you know if that post was created even when it was a draft?  I don't think it would have been publicly visible at that time.

**Comment by nelsonjchen** [comment]
There are two related issues. The default theme for the site only features
one single post. It should be just a list. It’s oddly hardcoded in. Maybe I
should just find a theme that does what we want anyway.

Yeah, I guess that’s the draft creation date. I can alter my meetup post
generation script to use the event date instead of the draft or post
creation date to generate the post date times. Alternatively I can change
the configuration to use an alternate field for sorting meetup post date
and times. 5e latter is cleaner and less hacks but I have the former out
fast.

I’ll see if I can get some combination of these two out soon.
